M48
; DRILL file {KiCad 9.0.6+dfsg-1} date 2025-12-05T21:57:11+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-12-05T21:57:11+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6+dfsg-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.100
%
G90
G05
T1
X52.35Y-52.35
X52.35Y-147.65
X147.65Y-52.35
X147.65Y-147.65
M30
